= Enums

[[AclTokenType]]
== AclTokenType

++++
 Acl token type is either "client" (meaning the token cannot modify ACL rules) or "management"
 (meaning the token is allowed to perform all actions).
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[CLIENT]]`CLIENT`|-
|[[MANAGEMENT]]`MANAGEMENT`|-
|===

[[ApolloWSMessageType]]
== ApolloWSMessageType

++++
 The link types.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[CONNECTION_INIT]]`CONNECTION_INIT`|-
|[[CONNECTION_TERMINATE]]`CONNECTION_TERMINATE`|-
|[[START]]`START`|-
|[[STOP]]`STOP`|-
|[[CONNECTION_ACK]]`CONNECTION_ACK`|-
|[[CONNECTION_ERROR]]`CONNECTION_ERROR`|-
|[[CONNECTION_KEEP_ALIVE]]`CONNECTION_KEEP_ALIVE`|-
|[[DATA]]`DATA`|-
|[[ERROR]]`ERROR`|-
|[[COMPLETE]]`COMPLETE`|-
|===

[[Attestation]]
== Attestation


[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NONE]]`NONE`|-
|[[DIRECT]]`DIRECT`|-
|[[INDIRECT]]`INDIRECT`|-
|===

[[AuthenticatorAttachment]]
== AuthenticatorAttachment


[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[CROSS_PLATFORM]]`CROSS_PLATFORM`|-
|[[PLATFORM]]`PLATFORM`|-
|===

[[BridgeEventType]]
== BridgeEventType

++++
 Bridge Event Types.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SOCKET_CREATED]]`SOCKET_CREATED`|+++
This event will occur when a new SockJS socket is created.
+++
|[[SOCKET_CLOSED]]`SOCKET_CLOSED`|+++
This event will occur when a SockJS socket is closed.
+++
|[[SOCKET_IDLE]]`SOCKET_IDLE`|+++
This event will occur when SockJS socket is on idle for longer period of time than configured.
+++
|[[SOCKET_PING]]`SOCKET_PING`|+++
This event will occur when the last ping timestamp is updated for the SockJS socket.
+++
|[[SEND]]`SEND`|+++
This event will occur when a message is attempted to be sent from the client to the server.
+++
|[[PUBLISH]]`PUBLISH`|+++
This event will occur when a message is attempted to be published from the client to the server.
+++
|[[RECEIVE]]`RECEIVE`|+++
This event will occur when a message is attempted to be delivered from the server to the client.
+++
|[[REGISTER]]`REGISTER`|+++
This event will occur when a client attempts to register a handler.
+++
|[[REGISTERED]]`REGISTERED`|+++
This event will occur when a client successfully registered. The raw message used for registration, notified with  event
+++
|[[UNREGISTER]]`UNREGISTER`|+++
This event will occur when a client attempts to unregister a handler.
+++
|===

[[CheckStatus]]
== CheckStatus

++++
 Represents an check status.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[PASSING]]`PASSING`|-
|[[WARNING]]`WARNING`|-
|[[CRITICAL]]`CRITICAL`|-
|===

[[CircuitBreakerState]]
== CircuitBreakerState

++++
 Circuit breaker states.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[OPEN]]`OPEN`|+++
The <code>OPEN</code> state. The circuit breaker is executing the fallback, and switches to the 
 state after the specified time.
+++
|[[CLOSED]]`CLOSED`|+++
The <code>CLOSED</code> state. The circuit breaker lets invocations pass and collects the failures. IF the number of
 failures reach the specified threshold, the cricuit breaker switches to the  state.
+++
|[[HALF_OPEN]]`HALF_OPEN`|+++
The <code>HALF_OPEN</code> state. The circuit breaker has been opened, and is now checking the current situation. It
 lets pass the next invocation and determines from the result (failure or success) if the circuit breaker can
 be switched to the  state again.
+++
|===

[[ClientAuth]]
== ClientAuth

++++
 Configures the engine to require/request client authentication.
 <p/>
 Created by manishk on 10/2/2015.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NONE]]`NONE`|+++
No client authentication is requested or required.
+++
|[[REQUEST]]`REQUEST`|+++
Accept authentication if presented by client. If this option is set and the client chooses
 not to provide authentication information about itself, the negotiations will continue.
+++
|[[REQUIRED]]`REQUIRED`|+++
Require client to present authentication, if not presented then negotiations will be declined.
+++
|===

[[ContainerSerializationStyle]]
== ContainerSerializationStyle

++++
 This enum contains supported object and arrays serialization styles. Every style has a enum value, and an array of
 strings to refeer to it.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[csv]]`csv`|+++
Comma separated values: "value1,value2,value3"
 aliases: "csv", "commaDelimited", "form", "simple"
+++
|[[ssv]]`ssv`|+++
Space separated values: "value1 value2 value3"
 aliases: "ssv", "spaceDelimited"
+++
|[[psv]]`psv`|+++
Pipe separated values: "value1|value2|value3"
 aliases: "psv", "pipeDelimited"
+++
|[[dsv]]`dsv`|+++
Dot delimited values: "value1.value2.value3"
 aliases: "dsv", "dotDelimited", "label"
+++
|[[simple_exploded_object]]`simple_exploded_object`|+++
For internal usage, don't use it
+++
|[[matrix_exploded_array]]`matrix_exploded_array`|+++
For internal usage, don't use it
+++
|===

[[DKIMSignAlgorithm]]
== DKIMSignAlgorithm

++++

 Signing Algorithm specified by DKIM spec.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[RSA_SHA1]]`RSA_SHA1`|-
|[[RSA_SHA256]]`RSA_SHA256`|-
|===

[[DnsResponseCode]]
== DnsResponseCode

++++
 Represents the possible response codes a server may send after receiving a
 query. A response code of 0 indicates no error.

++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NOERROR]]`NOERROR`|+++
ID 0, no error
+++
|[[FORMERROR]]`FORMERROR`|+++
ID 1, format error
+++
|[[SERVFAIL]]`SERVFAIL`|+++
ID 2, server failure
+++
|[[NXDOMAIN]]`NXDOMAIN`|+++
ID 3, name error
+++
|[[NOTIMPL]]`NOTIMPL`|+++
ID 4, not implemented
+++
|[[REFUSED]]`REFUSED`|+++
ID 5, operation refused
+++
|[[YXDOMAIN]]`YXDOMAIN`|+++
ID 6, domain name should not exist
+++
|[[YXRRSET]]`YXRRSET`|+++
ID 7, resource record set should not exist
+++
|[[NXRRSET]]`NXRRSET`|+++
ID 8, rrset does not exist
+++
|[[NOTAUTH]]`NOTAUTH`|+++
ID 9, not authoritative for zone
+++
|[[NOTZONE]]`NOTZONE`|+++
ID 10, name not in zone
+++
|[[BADVERS]]`BADVERS`|+++
ID 11, bad extension mechanism for version
+++
|[[BADSIG]]`BADSIG`|+++
ID 12, bad signature
+++
|[[BADKEY]]`BADKEY`|+++
ID 13, bad key
+++
|[[BADTIME]]`BADTIME`|+++
ID 14, bad timestamp
+++
|===

[[ExecStatus]]
== ExecStatus

++++
 The status of an execution.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[READY]]`READY`|+++
The job is ready, it can be running or terminated.
+++
|[[RUNNING]]`RUNNING`|+++
The job is running, it can be stopped or terminated.
+++
|[[STOPPED]]`STOPPED`|+++
The job is stopped, it can be running or terminated.
+++
|[[TERMINATED]]`TERMINATED`|+++
The job is terminated.
+++
|===

[[FetchDirection]]
== FetchDirection

++++
 Represents the fetch direction hint
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[FORWARD]]`FORWARD`|-
|[[REVERSE]]`REVERSE`|-
|[[UNKNOWN]]`UNKNOWN`|-
|===

[[HashAlgorithm]]
== HashAlgorithm


[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SHA512]]`SHA512`|+++
The default algorithm for backward compatible systems.

 Should not be used for new projects as OWASP recommends stronger hashing algorithms.
+++
|[[PBKDF2]]`PBKDF2`|+++
Stronger hashing algorithm, recommended by OWASP as of 2018.
+++
|===

[[HashSaltStyle]]
== HashSaltStyle

++++
 Password hash salt configuration.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NO_SALT]]`NO_SALT`|+++
Password hashes are not salted
+++
|[[COLUMN]]`COLUMN`|+++
Salt is in a separate column for each user in the database
+++
|[[EXTERNAL]]`EXTERNAL`|+++
Salt is NOT stored in the database, but defined as external value like application preferences or so
+++
|===

[[HealthState]]
== HealthState

++++
 Represents an health states.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[PASSING]]`PASSING`|-
|[[WARNING]]`WARNING`|-
|[[CRITICAL]]`CRITICAL`|-
|[[ANY]]`ANY`|-
|===

[[HttpVersion]]
== HttpVersion

++++
 Represents the version of the HTTP protocol.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[HTTP_1_0]]`HTTP_1_0`|-
|[[HTTP_1_1]]`HTTP_1_1`|-
|[[HTTP_2]]`HTTP_2`|-
|===

[[JsonEventType]]
== JsonEventType

++++
 The possibles types of link emitted by the link.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[START_OBJECT]]`START_OBJECT`|+++
Signals the start of a JSON object.
+++
|[[END_OBJECT]]`END_OBJECT`|+++
Signals the end of a JSON object.
+++
|[[START_ARRAY]]`START_ARRAY`|+++
Signals the start of a JSON array.
+++
|[[END_ARRAY]]`END_ARRAY`|+++
Signals the end of a JSON array.
+++
|[[VALUE]]`VALUE`|+++
Signals a JSON value.
+++
|===

[[Label]]
== Label

++++
 List of labels used in various Vert.x metrics. Labels that may not have bounded values are disabled by default.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[LOCAL]]`LOCAL`|+++
Local address in client-host or host-client connections (used in net, http and datagram domains)
+++
|[[REMOTE]]`REMOTE`|+++
Remote address in client-host or host-client connections (used in net and http domains)
+++
|[[HTTP_PATH]]`HTTP_PATH`|+++
Path of the URI for client or server requests (used in http domain)
+++
|[[HTTP_METHOD]]`HTTP_METHOD`|+++
Method (GET, POST, PUT, etc.) of an HTTP requests (used in http domain)
+++
|[[HTTP_CODE]]`HTTP_CODE`|+++
HTTP response code (used in http domain)
+++
|[[CLASS_NAME]]`CLASS_NAME`|+++
Class name. When used in error counters (in net, http, datagram and eventbus domains) it relates to an exception that occurred.
 When used in verticle domain, it relates to the verticle class name.
+++
|[[EB_ADDRESS]]`EB_ADDRESS`|+++
Event bus address
+++
|[[EB_SIDE]]`EB_SIDE`|+++
Event bus side of the metric, it can be either "local" or "remote"
+++
|[[EB_FAILURE]]`EB_FAILURE`|+++
Event bus failure name from a ReplyFailure object
+++
|[[POOL_TYPE]]`POOL_TYPE`|+++
Pool type, such as "worker" or "datasource" (used in pools domain)
+++
|[[POOL_NAME]]`POOL_NAME`|+++
Pool name (used in pools domain)
+++
|===

[[LoggerFormat]]
== LoggerFormat

++++
 The possible out of the box formats.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DEFAULT]]`DEFAULT`|+++
<i>remote-client</i> - - [<i>timestamp</i>] "<i>method</i> <i>uri</i> <i>version</i>" <i>status</i> <i>content-length</i> "<i>referrer</i>" "<i>user-agent</i>"
+++
|[[SHORT]]`SHORT`|+++
<i>remote-client</i> - <i>method</i> <i>uri</i> <i>version</i> <i>status</i> <i>content-length</i> <i>duration</i> ms
+++
|[[TINY]]`TINY`|+++
<i>method</i> <i>uri</i> <i>status</i> - <i>content-length</i> <i>duration</i>
+++
|[[CUSTOM]]`CUSTOM`|+++
Will use user defined formatter function.
+++
|===

[[LoginOption]]
== LoginOption

++++
 possible options for a login into a SMTP server
 <br>
 either DISABLED, OPTIONAL, REQUIRED or XOAUTH2
 <p>
 DISABLED means no login will be attempted
 <p>
 NONE means a login will be attempted if the server supports in and login credentials are set
 <p>
 REQUIRED means that a login will be attempted if the server supports it and the send operation will fail otherwise
 <p>
 XOAUTH2 means that a login will be attempted using Google Gmail Oauth2 tokens
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DISABLED]]`DISABLED`|-
|[[NONE]]`NONE`|-
|[[REQUIRED]]`REQUIRED`|-
|[[XOAUTH2]]`XOAUTH2`|-
|===

[[MatchType]]
== MatchType

++++
 The type of match.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[EQUALS]]`EQUALS`|-
|[[REGEX]]`REGEX`|-
|===

[[MessageCanonic]]
== MessageCanonic

++++

 Message canonicalization for DKIM.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SIMPLE]]`SIMPLE`|-
|[[RELAXED]]`RELAXED`|-
|===

[[MetricsDomain]]
== MetricsDomain

++++
 Metric domains with their associated prefixes.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NET_SERVER]]`NET_SERVER`|+++
Net server metrics.
+++
|[[NET_CLIENT]]`NET_CLIENT`|+++
Net client metrics.
+++
|[[HTTP_SERVER]]`HTTP_SERVER`|+++
Http server metrics.
+++
|[[HTTP_CLIENT]]`HTTP_CLIENT`|+++
Http client metrics.
+++
|[[DATAGRAM_SOCKET]]`DATAGRAM_SOCKET`|+++
Datagram socket metrics.
+++
|[[EVENT_BUS]]`EVENT_BUS`|+++
Event bus metrics.
+++
|[[NAMED_POOLS]]`NAMED_POOLS`|+++
Named pools metrics.
+++
|[[VERTICLES]]`VERTICLES`|+++
Verticle metrics.
+++
|===

[[MySQLSetOption]]
== MySQLSetOption

++++
 MySQL set options which can be used by link.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[MYSQL_OPTION_MULTI_STATEMENTS_ON]]`MYSQL_OPTION_MULTI_STATEMENTS_ON`|-
|[[MYSQL_OPTION_MULTI_STATEMENTS_OFF]]`MYSQL_OPTION_MULTI_STATEMENTS_OFF`|-
|===

[[OAuth2FlowType]]
== OAuth2FlowType

++++
 OAuth2 Flows
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[AUTH_CODE]]`AUTH_CODE`|+++
The authorization code is obtained by using an authorization server
 as an intermediary between the client and resource owner.  Instead of
 requesting authorization directly from the resource owner, the client
 directs the resource owner to an authorization server (via its
 user-agent as defined in [RFC2616]), which in turn directs the
 resource owner back to the client with the authorization code.
 <p>
 Before directing the resource owner back to the client with the
 authorization code, the authorization server authenticates the
 resource owner and obtains authorization.  Because the resource owner
 only authenticates with the authorization server, the resource
 owner's credentials are never shared with the client.
 <p>
 The authorization code provides a few important security benefits,
 such as the ability to authenticate the client, as well as the
 transmission of the access token directly to the client without
 passing it through the resource owner's user-agent and potentially
 exposing it to others, including the resource owner.
+++
|[[IMPLICIT]]`IMPLICIT`|+++
The implicit grant is a simplified authorization code flow optimized
 for clients implemented in a browser using a scripting language such
 as JavaScript.  In the implicit flow, instead of issuing the client
 an authorization code, the client is issued an access token directly
 (as the result of the resource owner authorization).  The grant type
 is implicit, as no intermediate credentials (such as an authorization
 code) are issued (and later used to obtain an access token).
 <p>
 When issuing an access token during the implicit grant flow, the
 authorization server does not authenticate the client.  In some
 cases, the client identity can be verified via the redirection URI
 used to deliver the access token to the client.  The access token may
 be exposed to the resource owner or other applications with access to
 the resource owner's user-agent.
 <p>
 Implicit grants improve the responsiveness and efficiency of some
 clients (such as a client implemented as an in-browser application),
 since it reduces the number of round trips required to obtain an
 access token.  However, this convenience should be weighed against
 the security implications of using implicit grants, especially when the
 authorization code grant type is available.
+++
|[[PASSWORD]]`PASSWORD`|+++
The resource owner password credentials (i.e., username and password)
 can be used directly as an authorization grant to obtain an access
 token.  The credentials should only be used when there is a high
 degree of trust between the resource owner and the client (e.g., the
 client is part of the device operating system or a highly privileged
 application), and when other authorization grant types are not
 available (such as an authorization code).
 <p>
 Even though this grant type requires direct client access to the
 resource owner credentials, the resource owner credentials are used
 for a single request and are exchanged for an access token.  This
 grant type can eliminate the need for the client to store the
 resource owner credentials for future use, by exchanging the
 credentials with a long-lived access token or refresh token.
+++
|[[CLIENT]]`CLIENT`|+++
The client credentials (or other forms of client authentication) can
 be used as an authorization grant when the authorization scope is
 limited to the protected resources under the control of the client,
 or to protected resources previously arranged with the authorization
 server.  Client credentials are used as an authorization grant
 typically when the client is acting on its own behalf (the client is
 also the resource owner) or is requesting access to protected
 resources based on an authorization previously arranged with the
 authorization server.
+++
|[[AUTH_JWT]]`AUTH_JWT`|+++
RFC7523
+++
|===

[[ParameterLocation]]
== ParameterLocation

++++
 ParameterLocation describe the location of parameter inside HTTP Request
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[HEADER]]`HEADER`|-
|[[QUERY]]`QUERY`|-
|[[PATH]]`PATH`|-
|[[FILE]]`FILE`|-
|[[BODY_FORM]]`BODY_FORM`|-
|[[BODY]]`BODY`|-
|[[BODY_JSON]]`BODY_JSON`|-
|[[BODY_XML]]`BODY_XML`|-
|[[COOKIE]]`COOKIE`|-
|===

[[ParameterType]]
== ParameterType

++++
 ParameterType contains prebuilt type validators. To access to ParameterTypeValidator of every ParameterType, use
 link
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[GENERIC_STRING]]`GENERIC_STRING`|+++
STRING Type accept every string
+++
|[[EMAIL]]`EMAIL`|-
|[[URI]]`URI`|-
|[[BOOL]]`BOOL`|+++
It allows true, false, t, f, 1, 0
+++
|[[INT]]`INT`|+++
INT type does the validation with Integer.parseInt(value)
+++
|[[FLOAT]]`FLOAT`|+++
FLOAT type does the validation with Float.parseFloat(value)
+++
|[[DOUBLE]]`DOUBLE`|+++
DOUBLE type does the validation with Double.parseDouble(value)
+++
|[[DATE]]`DATE`|+++
DATE as defined by full-date - RFC3339
+++
|[[DATETIME]]`DATETIME`|+++
DATETIME as defined by date-time - RFC3339
+++
|[[TIME]]`TIME`|+++
TIME as defined by partial-time - RFC3339
+++
|[[BASE64]]`BASE64`|-
|[[IPV4]]`IPV4`|-
|[[IPV6]]`IPV6`|-
|[[HOSTNAME]]`HOSTNAME`|-
|[[UUID]]`UUID`|+++
UUID as defined by RFC4122
+++
|===

[[ProxyType]]
== ProxyType

++++
 The type of a TCP proxy server.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[HTTP]]`HTTP`|+++
HTTP CONNECT ssl proxy
+++
|[[SOCKS4]]`SOCKS4`|+++
SOCKS4/4a tcp proxy
+++
|[[SOCKS5]]`SOCKS5`|+++
SOCSK5 tcp proxy
+++
|===

[[RedisClientType]]
== RedisClientType

++++
 Define what kind of behavior is expected from the client.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[STANDALONE]]`STANDALONE`|+++
The client should work in single server mode (the default).
+++
|[[SENTINEL]]`SENTINEL`|+++
The client should work in sentinel mode. When this mode is active
 use the link to define which role to get the client
 connection to.
+++
|[[CLUSTER]]`CLUSTER`|+++
The client should work in cluster mode. When this mode is active
 use the link to define when slave nodes can be used
 for read only queries.
+++
|===

[[RedisRole]]
== RedisRole

++++
 Define which kind of role to be used in HA mode.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[MASTER]]`MASTER`|+++
Use a MASTER node connection.
+++
|[[SLAVE]]`SLAVE`|+++
Use a SLAVE node connection.
+++
|[[SENTINEL]]`SENTINEL`|+++
Use a SENTINEL node connection.
+++
|===

[[RedisSlaves]]
== RedisSlaves

++++
 When should Redis Slave nodes be used for queries.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NEVER]]`NEVER`|+++
Never use SLAVES, queries are always run on a MASTER node.
+++
|[[SHARE]]`SHARE`|+++
Queries can be randomly run on both MASTER and SLAVE nodes.
+++
|[[ALWAYS]]`ALWAYS`|+++
Queries are always run on SLAVE nodes (never on MASTER node).
+++
|===

[[ReplyFailure]]
== ReplyFailure

++++
 Represents the type of reply failure
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[TIMEOUT]]`TIMEOUT`|+++
The message send failed because no reply was received before the timeout time.
+++
|[[NO_HANDLERS]]`NO_HANDLERS`|+++
The message send failed because no handlers were available to handle the message.
+++
|[[RECIPIENT_FAILURE]]`RECIPIENT_FAILURE`|+++
The message send failed because the recipient actively sent back a failure (rejected the message)
+++
|===

[[ResponseType]]
== ResponseType

++++
 Define the response types that the client can receive from REDIS.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SIMPLE]]`SIMPLE`|+++
C String simple String.
+++
|[[ERROR]]`ERROR`|+++
C String simple String representing an error.
+++
|[[INTEGER]]`INTEGER`|+++
64 bit integer value.
+++
|[[BULK]]`BULK`|+++
byte array value.
+++
|[[MULTI]]`MULTI`|+++
List of multiple bulk responses.
+++
|===

[[ResultSetConcurrency]]
== ResultSetConcurrency

++++
 Represents the resultset concurrency hint
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[READ_ONLY]]`READ_ONLY`|-
|[[UPDATABLE]]`UPDATABLE`|-
|===

[[ResultSetType]]
== ResultSetType

++++
 Represents the resultset type hint
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[FORWARD_ONLY]]`FORWARD_ONLY`|-
|[[SCROLL_INSENSITIVE]]`SCROLL_INSENSITIVE`|-
|[[SCROLL_SENSITIVE]]`SCROLL_SENSITIVE`|-
|===

[[ShiroAuthRealmType]]
== ShiroAuthRealmType

++++
 The type of the Shiro auth realm
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[PROPERTIES]]`PROPERTIES`|+++
The realm is a Shiro properties auth provider
+++
|[[LDAP]]`LDAP`|+++
The realm is a Shiro LDAP auth provider
+++
|===

[[SslMode]]
== SslMode

++++
 This parameter specifies the desired security state of the connection to the server.
 More information can be found in <a href="https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode">MySQL Reference Manual</a>
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DISABLED]]`DISABLED`|+++
establish an unencrypted connection.
+++
|[[PREFERRED]]`PREFERRED`|+++
establish an encrypted connection if the server supports encrypted connections, falling back to an unencrypted connection if an encrypted connection cannot be established.
+++
|[[REQUIRED]]`REQUIRED`|+++
establish an encrypted connection if the server supports encrypted connections. The connection attempt fails if an encrypted connection cannot be established.
+++
|[[VERIFY_CA]]`VERIFY_CA`|+++
Like REQUIRED, but additionally verify the server Certificate Authority (CA) certificate against the configured CA certificates. The connection attempt fails if no valid matching CA certificates are found.
+++
|[[VERIFY_IDENTITY]]`VERIFY_IDENTITY`|+++
Like VERIFY_CA, but additionally perform host name identity verification by checking the host name the client uses for connecting to the server against the identity in the certificate that the server sends to the client.
+++
|===

[[SslMode]]
== SslMode

++++
 The different values for the sslmode parameter provide different levels of
 protection. See more information in <a href=
 "https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION">Protection
 Provided in Different Modes</a>.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DISABLE]]`DISABLE`|+++
only try a non-SSL connection.
+++
|[[ALLOW]]`ALLOW`|+++
first try a non-SSL connection; if that fails, try an SSL connection.
+++
|[[PREFER]]`PREFER`|+++
first try an SSL connection; if that fails, try a non-SSL connection.
+++
|[[REQUIRE]]`REQUIRE`|+++
only try an SSL connection. If a root CA file is present, verify the certificate in the same way as if verify-ca was specified.
+++
|[[VERIFY_CA]]`VERIFY_CA`|+++
only try an SSL connection, and verify that the server certificate is issued by a trusted certificate authority (CA).
+++
|[[VERIFY_FULL]]`VERIFY_FULL`|+++
only try an SSL connection, verify that the server certificate is issued by a trusted CA and that the requested server host name matches that in the certificate.
+++
|===

[[StartTLSOptions]]
== StartTLSOptions

++++
 possible options for a secure connection using TLS
 <br>
 either DISABLED, OPTIONAL or REQUIRED
 <p>
 DISABLED means STARTTLS will not be used in any case
 <p>
 OPTIONS means STARTTLS will be used if the server supports it and a plain connection will be used otherwise
 please note that this option is not a secure as it seems since a MITM attacker can remove the STARTTLS line
 from the capabilities reply.
 <p>
 REQUIRED means that STARTTLS will be used if the server supports it and the send operation will fail otherwise
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[DISABLED]]`DISABLED`|-
|[[OPTIONAL]]`OPTIONAL`|-
|[[REQUIRED]]`REQUIRED`|-
|===

[[Status]]
== Status

++++
 Service publication status.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[UP]]`UP`|+++
The service is published and is accessible.
+++
|[[DOWN]]`DOWN`|+++
The service has been withdrawn, it is not accessible anymore.
+++
|[[OUT_OF_SERVICE]]`OUT_OF_SERVICE`|+++
The service is still published, but not accessible (maintenance).
+++
|[[UNKNOWN]]`UNKNOWN`|+++
Unknown status.
+++
|===

[[TransactionIsolation]]
== TransactionIsolation

++++
 Represents a Transaction Isolation Level
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[READ_UNCOMMITTED]]`READ_UNCOMMITTED`|+++
Implements dirty read, or isolation level 0 locking, which means that no shared locks are issued and no exclusive
 locks are honored. When this option is set, it is possible to read uncommitted or dirty data; values in the data
 can be changed and rows can appear or disappear in the data set before the end of the transaction. This is the
 least restrictive of the four isolation levels.
+++
|[[READ_COMMITTED]]`READ_COMMITTED`|+++
Specifies that shared locks are held while the data is being read to avoid dirty reads, but the data can be changed
 before the end of the transaction, resulting in nonrepeatable reads or phantom data.
+++
|[[REPEATABLE_READ]]`REPEATABLE_READ`|+++
Locks are placed on all data that is used in a query, preventing other users from updating the data, but new
 phantom rows can be inserted into the data set by another user and are included in later reads in the current
 transaction. Because concurrency is lower than the default isolation level, use this option only when necessary.
+++
|[[SERIALIZABLE]]`SERIALIZABLE`|+++
Places a range lock on the data set, preventing other users from updating or inserting rows into the data set until
 the transaction is complete. This is the most restrictive of the four isolation levels. Because concurrency is
 lower, use this option only when necessary.
+++
|[[NONE]]`NONE`|+++
For engines that support it, none isolation means that each statement would essentially be its own transaction.
+++
|===

[[Transport]]
== Transport

++++
 The available SockJS transports
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[WEBSOCKET]]`WEBSOCKET`|+++
<a href="http://www.rfc-editor.org/rfc/rfc6455.txt">rfc 6455</a>
+++
|[[EVENT_SOURCE]]`EVENT_SOURCE`|+++
<a href="http://dev.w3.org/html5/eventsource/">Event source</a>
+++
|[[HTML_FILE]]`HTML_FILE`|+++
<a href="http://cometdaily.com/2007/11/18/ie-activexhtmlfile-transport-part-ii/">HtmlFile</a>.
+++
|[[JSON_P]]`JSON_P`|+++
Slow and old fashioned <a hred="https://developer.mozilla.org/en/DOM/window.postMessage">JSONP polling</a>.
 This transport will show "busy indicator" (aka: "spinning wheel") when sending data.
+++
|[[XHR]]`XHR`|+++
Long-polling using <a hred="https://secure.wikimedia.org/wikipedia/en/wiki/XMLHttpRequest#Cross-domain_requests">cross domain XHR</a>
+++
|===

[[UserVerification]]
== UserVerification


[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[REQUIRED]]`REQUIRED`|-
|[[PREFERRED]]`PREFERRED`|-
|[[DISCOURAGED]]`DISCOURAGED`|-
|===

[[WebsocketVersion]]
== WebsocketVersion

++++
 Represents the WebSocket version
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[V00]]`V00`|-
|[[V07]]`V07`|-
|[[V08]]`V08`|-
|[[V13]]`V13`|-
|===

[[WriteOption]]
== WriteOption

++++
 Enum representing the mongoDB Java Driver's link
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[ACKNOWLEDGED]]`ACKNOWLEDGED`|+++

+++
|[[UNACKNOWLEDGED]]`UNACKNOWLEDGED`|+++

+++
|[[FSYNCED]]`FSYNCED`|+++

+++
|[[JOURNALED]]`JOURNALED`|+++

+++
|[[REPLICA_ACKNOWLEDGED]]`REPLICA_ACKNOWLEDGED`|+++

+++
|[[MAJORITY]]`MAJORITY`|+++

+++
|===

