package io.vertx.kotlin.ext.consul

import io.vertx.ext.consul.PreparedQueryDefinition

/**
 * A function providing a DSL for building [io.vertx.ext.consul.PreparedQueryDefinition] objects.
 *
 * Defines a prepared query.
 *
 * @param dcs  Specifies a fixed list of remote datacenters to forward the query to if there are no healthy nodes in the local datacenter. Datacenters are queried in the order given in the list. If this option is combined with NearestN, then the NearestN queries will be performed first, followed by the list given by Datacenters. A given datacenter will only be queried one time during a failover, even if it is selected by both NearestN and is listed in Datacenters.
 * @param dnsTtl  Set the TTL duration when query results are served over DNS. If this is specified, it will take precedence over any Consul agent-specific configuration.
 * @param id  Set ID of the query, always generated by Consul
 * @param meta  Set a list of user-defined key/value pairs that will be used for filtering the query results to nodes with the given metadata values present.
 * @param name  Set an optional friendly name that can be used to execute a query instead of using its ID
 * @param nearestN  Specifies that the query will be forwarded to up to NearestN other datacenters based on their estimated network round trip time using Network Coordinates from the WAN gossip pool. The median round trip time from the server handling the query to the servers in the remote datacenter is used to determine the priority.
 * @param passing  Specifies the behavior of the query's health check filtering. If this is set to false, the results will include nodes with checks in the passing as well as the warning states. If this is set to true, only nodes with checks in the passing state will be returned.
 * @param service  Set the name of the service to query
 * @param session  Set the ID of an existing session. This provides a way to automatically remove a prepared query when the given session is invalidated. If not given the prepared query must be manually removed when no longer needed.
 * @param tags  Set a list of service tags to filter the query results. For a service to pass the tag filter it must have all of the required tags, and none of the excluded tags (prefixed with `!`).
 * @param templateRegexp  Set regular expression which is used to extract fields from the entire name, once this template is selected.
 * @param templateType  The template type, which must be <code>name_prefix_match</code>. This means that the template will apply to any query lookup with a name whose prefix matches the Name field of the template.
 * @param token  Set the ACL token to use each time the query is executed. This allows queries to be executed by clients with lesser or even no ACL Token, so this should be used with care.
 *
 * <p/>
 * NOTE: This function has been automatically generated from the [io.vertx.ext.consul.PreparedQueryDefinition original] using Vert.x codegen.
 */
fun preparedQueryDefinitionOf(
  dcs: Iterable<String>? = null,
  dnsTtl: String? = null,
  id: String? = null,
  meta: Map<String, String>? = null,
  name: String? = null,
  nearestN: Int? = null,
  passing: Boolean? = null,
  service: String? = null,
  session: String? = null,
  tags: Iterable<String>? = null,
  templateRegexp: String? = null,
  templateType: String? = null,
  token: String? = null): PreparedQueryDefinition = io.vertx.ext.consul.PreparedQueryDefinition().apply {

  if (dcs != null) {
    this.setDcs(dcs.toList())
  }
  if (dnsTtl != null) {
    this.setDnsTtl(dnsTtl)
  }
  if (id != null) {
    this.setId(id)
  }
  if (meta != null) {
    this.setMeta(meta)
  }
  if (name != null) {
    this.setName(name)
  }
  if (nearestN != null) {
    this.setNearestN(nearestN)
  }
  if (passing != null) {
    this.setPassing(passing)
  }
  if (service != null) {
    this.setService(service)
  }
  if (session != null) {
    this.setSession(session)
  }
  if (tags != null) {
    this.setTags(tags.toList())
  }
  if (templateRegexp != null) {
    this.setTemplateRegexp(templateRegexp)
  }
  if (templateType != null) {
    this.setTemplateType(templateType)
  }
  if (token != null) {
    this.setToken(token)
  }
}

/**
 * A function providing a DSL for building [io.vertx.ext.consul.PreparedQueryDefinition] objects.
 *
 * Defines a prepared query.
 *
 * @param dcs  Specifies a fixed list of remote datacenters to forward the query to if there are no healthy nodes in the local datacenter. Datacenters are queried in the order given in the list. If this option is combined with NearestN, then the NearestN queries will be performed first, followed by the list given by Datacenters. A given datacenter will only be queried one time during a failover, even if it is selected by both NearestN and is listed in Datacenters.
 * @param dnsTtl  Set the TTL duration when query results are served over DNS. If this is specified, it will take precedence over any Consul agent-specific configuration.
 * @param id  Set ID of the query, always generated by Consul
 * @param meta  Set a list of user-defined key/value pairs that will be used for filtering the query results to nodes with the given metadata values present.
 * @param name  Set an optional friendly name that can be used to execute a query instead of using its ID
 * @param nearestN  Specifies that the query will be forwarded to up to NearestN other datacenters based on their estimated network round trip time using Network Coordinates from the WAN gossip pool. The median round trip time from the server handling the query to the servers in the remote datacenter is used to determine the priority.
 * @param passing  Specifies the behavior of the query's health check filtering. If this is set to false, the results will include nodes with checks in the passing as well as the warning states. If this is set to true, only nodes with checks in the passing state will be returned.
 * @param service  Set the name of the service to query
 * @param session  Set the ID of an existing session. This provides a way to automatically remove a prepared query when the given session is invalidated. If not given the prepared query must be manually removed when no longer needed.
 * @param tags  Set a list of service tags to filter the query results. For a service to pass the tag filter it must have all of the required tags, and none of the excluded tags (prefixed with `!`).
 * @param templateRegexp  Set regular expression which is used to extract fields from the entire name, once this template is selected.
 * @param templateType  The template type, which must be <code>name_prefix_match</code>. This means that the template will apply to any query lookup with a name whose prefix matches the Name field of the template.
 * @param token  Set the ACL token to use each time the query is executed. This allows queries to be executed by clients with lesser or even no ACL Token, so this should be used with care.
 *
 * <p/>
 * NOTE: This function has been automatically generated from the [io.vertx.ext.consul.PreparedQueryDefinition original] using Vert.x codegen.
 */
@Deprecated(
  message = "This function will be removed in a future version",
  replaceWith = ReplaceWith("preparedQueryDefinitionOf(dcs, dnsTtl, id, meta, name, nearestN, passing, service, session, tags, templateRegexp, templateType, token)")
)
fun PreparedQueryDefinition(
  dcs: Iterable<String>? = null,
  dnsTtl: String? = null,
  id: String? = null,
  meta: Map<String, String>? = null,
  name: String? = null,
  nearestN: Int? = null,
  passing: Boolean? = null,
  service: String? = null,
  session: String? = null,
  tags: Iterable<String>? = null,
  templateRegexp: String? = null,
  templateType: String? = null,
  token: String? = null): PreparedQueryDefinition = io.vertx.ext.consul.PreparedQueryDefinition().apply {

  if (dcs != null) {
    this.setDcs(dcs.toList())
  }
  if (dnsTtl != null) {
    this.setDnsTtl(dnsTtl)
  }
  if (id != null) {
    this.setId(id)
  }
  if (meta != null) {
    this.setMeta(meta)
  }
  if (name != null) {
    this.setName(name)
  }
  if (nearestN != null) {
    this.setNearestN(nearestN)
  }
  if (passing != null) {
    this.setPassing(passing)
  }
  if (service != null) {
    this.setService(service)
  }
  if (session != null) {
    this.setSession(session)
  }
  if (tags != null) {
    this.setTags(tags.toList())
  }
  if (templateRegexp != null) {
    this.setTemplateRegexp(templateRegexp)
  }
  if (templateType != null) {
    this.setTemplateType(templateType)
  }
  if (token != null) {
    this.setToken(token)
  }
}

