name: CI matrix (5.x)
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 11
          - os: ubuntu-latest
            jdk: 17
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ inputs.branch }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
    secrets: inherit
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: CI
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ inputs.branch }}
      jdk: 11
    secrets: inherit
